spring.application.name=BibliotecaApp

# Configuración de la base de datos SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BibliotecaDB;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sql
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver