spring.application.name=BibliotecaApp

# Configuración de la base de datos SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BibliotecaDB;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sql
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile